language: node_js
sudo: false
node_js:
- '5.1'

env:
  global:
  - GH_REF: github.com/your-user/repo.git
  - secure: add-secure-hash
install:
- npm install karma-es6-shim
- npm install
before_script:
# - ./BrowserStackLocal-linux $bs_key localhost,9001,0 &
# - npm start &
# - sleep 5
after_script:
- process.exit()
after_success:
- chmod +x ./gulp/deploy.sh
- ./gulp/deploy.sh
cache:
  directories:
  - $HOME/.nvm
